# Generated by Django 5.2.5 on 2026-09-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0005_seed_product_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='recommended_for', to='keyur.product'),
        ),
    ]
