# Generated by Django 5.2.5 on 2026-09-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0006_delete_products_product_recommended_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation_image',
            field=models.ImageField(blank=True, help_text='Optional image to use in recommendation cards.', null=True, upload_to='recommendations/'),
        ),
    ]
