# Generated by Django 5.2.5 on 2026-09-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0007_product_recommendation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommendation_limit',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of products to show in recommendations.'),
        ),
    ]
