# Generated by Django 5.2.5 on 2026-09-08 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0008_product_recommendation_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommendation_limit',
        ),
    ]
