# Generated by Django 5.2.5 on 2026-09-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0010_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommendation_image',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='image',
        ),
    ]
