# Generated by Django 5.2.5 on 2026-09-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0011_remove_product_recommendation_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
