# Generated by Django 5.2.5 on 2026-09-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyur', '0012_recommendation_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='separate_recommendations', to='keyur.product'),
        ),
    ]
